name: Blank Issue Form
description: Standard Expunge Assist issue form
title: "Provide a descriptive title for the issue"
labels:
  - "feature: missing"
  - "issue level: missing"
  - "priority: missing"
  - "role: missing"
  - "size: missing"
body:
  - type: input
    id: title
    attributes:
      label: "Title"
      description: "Provide a brief and descriptive title for the issue"
      placeholder: "e.g., Bug in user login process"
    validations:
      required: true
  - type: textarea
    id: overview
    attributes:
      label: "Overview"
      description: "Text here that clearly states the purpose of this issue in 2 sentences or less."
      placeholder: "Provide a brief description of the issue."
    validations:
      required: true
  - type: checkboxes
    id: action_items
    attributes:
      label: "Action Items"
      description: "List the tasks that need to be completed."
      options:
        - label: "Research and document initial findings"
        - label: "Outline steps to resolve the issue"
        - label: "Divide into separate tasks if needed"
  - type: input
    id: resources
    attributes:
      label: "Resources/Notes"
      description: "If there is a website which has documentation that helps with this issue, provide the link(s) here."
      placeholder: "Add relevant resources or notes here, such as links to documentation."
