name: "Blank Issue Form"
description: "Standard Expunge Assist issue form"
about: Consistent formatting make issues concise and easy to navigate
labels:
  [
    feature: missing,
    issue level: missing,
    priority: missing,
    role: missing,
    size: missing',
  ]

body:
  - type: markdown
    id: overview
    attributes:
      label: Overview
      description: Clearly state the purpose of this issue in 2 sentences or less
    validations:
      required: true
  - type: textarea
    id: action-items
    attributes:
      label: Action Items
      description: "If this is the beginning of the task this is most likely something to be researched and documented."
    validations:
      required: true
  - type: textarea
    id: resources-instructions
    attributes:
      label: "Resources/Instructions"
      description: "If the issue has already been researched, and the course of action is clear, this will describe the steps.  However, if the steps can be divided into tasks for more than one person, we recommend dividing it up into separate issues, or assigning it as a pair programming task."
    validations:
      required: true
