/**
 * this constant that references a step in the form
 *
 * @type FORM_STEP
 */
export const FORM_STEPS = {
  NONE: 'FORM_STEPS.NONE',
  BEFORE_YOU_BEGIN: 'FORM_STEPS.BEFORE_YOU_BEGIN',
  INTRODUCTION: 'FORM_STEPS.INTRODUCTION',
  INVOLVEMENT_GENERIC: 'FORM_STEPS.INVOLVEMENT_GENERIC',
  INVOLVEMENT: {
    JOB: 'FORM_STEPS.INVOLVEMENT.JOB',
    COMMUNITY_SERVICE: 'FORM_STEPS.INVOLVEMENT.COMMUNITY_SERVICE',
    RECOVERY: 'FORM_STEPS.INVOLVEMENT.RECOVERY',
    SCHOOL: 'FORM_STEPS.INVOLVEMENT.SCHOOL',
    PARENTING: 'FORM_STEPS.INVOLVEMENT.PARENTING',
    UNEMPLOYED: 'FORM_STEPS.INVOLVEMENT.UNEMPLOYED',
  },
  GOALS: 'FORM_STEPS.GOALS',
  WHY: 'FORM_STEPS.WHY',
  FINALIZE: 'FORM_STEPS.FINALIZE',
  PREVIEWING: 'FORM_STEPS.PREVIEWING',
  EDITING: 'FORM_STEPS.EDITING',
  DOWNLOAD: 'FORM_STEPS.DOWNLOAD',
};

/**
 * map of a constant to the page url
 *
 * @type PAGES
 */
export const PAGES = {
  [FORM_STEPS.NONE]: '',
  [FORM_STEPS.BEFORE_YOU_BEGIN]: 'start',
  [FORM_STEPS.INTRODUCTION]: 'intro',
  [FORM_STEPS.INVOLVEMENT_GENERIC]: 'involvement',
  [FORM_STEPS.INVOLVEMENT.JOB]: 'job',
  [FORM_STEPS.INVOLVEMENT.RECOVERY]: 'recovery',
  [FORM_STEPS.INVOLVEMENT.SCHOOL]: 'school',
  [FORM_STEPS.INVOLVEMENT.PARENTING]: 'parenting',
  [FORM_STEPS.INVOLVEMENT.UNEMPLOYED]: 'unemployed',
  [FORM_STEPS.GOALS]: 'goals',
  [FORM_STEPS.WHY]: 'why',
  [FORM_STEPS.FINALIZE]: 'finalize',
  [FORM_STEPS.EDITING]: 'edit',
  [FORM_STEPS.DOWNLOAD]: 'download',
};

/**
 * map of PAGES to a FORM_STEP
 *
 * @type URL
 */
export const URL: { [key: string]: string } = {};
Object.keys(PAGES).forEach((pageKey) => {
  const pageValue = PAGES[pageKey];
  URL[pageValue] = pageKey;
});

/**
 * @param {FORM_STEPS} step
 * @returns {FORM_STEPS}
 */
export function getNextFormStep(step: string) {
  switch (step) {
    case FORM_STEPS.NONE:
      return FORM_STEPS.BEFORE_YOU_BEGIN;

    case FORM_STEPS.BEFORE_YOU_BEGIN:
      return FORM_STEPS.INTRODUCTION;

    case FORM_STEPS.INTRODUCTION:
      return FORM_STEPS.INVOLVEMENT.JOB;

    case FORM_STEPS.INVOLVEMENT.JOB:
      return FORM_STEPS.INVOLVEMENT.COMMUNITY_SERVICE;

    case FORM_STEPS.INVOLVEMENT.COMMUNITY_SERVICE:
      return FORM_STEPS.INVOLVEMENT.RECOVERY;

    case FORM_STEPS.INVOLVEMENT.RECOVERY:
      return FORM_STEPS.INVOLVEMENT.SCHOOL;

    case FORM_STEPS.INVOLVEMENT.SCHOOL:
      return FORM_STEPS.INVOLVEMENT.PARENTING;

    case FORM_STEPS.INVOLVEMENT.PARENTING:
      return FORM_STEPS.INVOLVEMENT.UNEMPLOYED;

    case FORM_STEPS.INVOLVEMENT.UNEMPLOYED:
      return FORM_STEPS.GOALS;

    case FORM_STEPS.GOALS:
      return FORM_STEPS.WHY;

    case FORM_STEPS.WHY:
      return FORM_STEPS.FINALIZE;

    case FORM_STEPS.FINALIZE:
    default:
      return FORM_STEPS.NONE;
  }
}
