name: Prettier Lint

on: [pull_request]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16"
      - name: Debug Information
        run: |
          echo "Node.js version:"
          node --version
          echo "NPM version:"
          npm --version
          echo "Prettier version:"
          npx prettier --version
          echo "Listing .prettierrc.json:"
          cat .prettierrc.json
          echo "Listing all files to be checked:"
          ls -R

      - name: Install Dependencies
        run: npm install
        working-directory: ./products/statement-generator
      - name: Check Prettier Format
        run: npx prettier --check 'products/statement-generator/**/*.{js,jsx,ts,tsx,html,css,json,md}'
