name: Monthly roster update

on:
  schedule:
    - cron: "0 0 1 * *" # Runs on the 1st of every month at 00:00 UTC

jobs:
  duplicate-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Duplicate Issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = 1065;
            const issue = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber
            });

            const newIssue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `${new Date().toISOString().slice(0, 10)} ${issue.data.title}`,
              body: issue.data.body,
              labels: issue.data.labels.map(label => label.name),
              milestone: issue.data.milestone ? issue.data.milestone.number : undefined
            });


            if (issue.data.project_url) {
              const projectId = issue.data.project_url.split('/').pop();
              const project = await github.rest.projects.get({
                project_id: projectId
              });
              const columnId = project.data.columns.find(column => column.name === "To do").id;
              await github.rest.projects.createCard({
                column_id: columnId,
                content_id: newIssue.data.id,
                content_type: 'Issue'
              });
            }
