name: Monthly roster update

on:
  schedule:
    - cron: "0 0 1 * *" # Runs on the 1st of every month at 00:00 UTC

jobs:
  duplicate-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Duplicate Issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = 1065; 


            const issue = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber
            });


            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `${new Date().toISOString().slice(0, 10)} ${issue.data.title}`,
              body: issue.data.body
            });
