name: Weekly Label Check

on:
  schedule:
    # Runs every Sunday at 00:00 UTC
    - cron: "0 0 * * 0"

jobs:
  Add-Missing-Labels-To-Issues:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install @octokit/rest

      - name: Process Open Issues
        run: node .github/workflows/scripts/weekly-label-check.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
